import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import Header from './Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
      </head>
      <body className={'min-h-screen flex flex-col relative' +inter.className}>
       <Header />
        <div className="flex-1">
      
        
        {children}
        </div>
        <footer className='flex item-center flex-wrap justify-center border-t border-solid border-slate-700 p-10'>
        <i className="fa-brands fa-twitter text-slate-700 hover:text-slate-500 cursor-pointer text-2xl"></i>
        </footer>
        <div id="portal"></div>
        </body>
    </html>
  )
}
